title: Jekyll Minimal Blog
email: your-email@example.com
description: Write an awesome description for your new site here.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
