title: Jekyll Minimal Blog
email: your-email@example.com
description: Write an awesome description for your new site here.
domain: "darenhart.github.io"
url: "https://darenhart.github.io"
baseurl: "/jekyll-minimal-blog/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
